add vim modeline

diff --git a/common/backdrop-randomizer.in b/common/backdrop-randomizer.in
--- a/common/backdrop-randomizer.in
+++ b/common/backdrop-randomizer.in
@@ -17,12 +17,12 @@ export BLD="\e[01m" RED="\e[01;31m" GRN="\e[01;32m" YLW="\e[01;33m" NRM="\e[00m"
 cfg_file="$XDG_CONFIG_HOME/backdrop-randomizer.conf"
 
 check() {
-	if [[ ! -f "$cfg_file" ]]; then
-		#	create $XDG_CONFIG_HOME/backdrop-randomizer.conf
-		echo '------------------------------------------------------------'
-		echo ' No config file found so creating a fresh one.'
-		echo
-		cat <<EOF > "$XDG_CONFIG_HOME/backdrop-randomizer.conf"
+  if [[ ! -f "$cfg_file" ]]; then
+    #	create $XDG_CONFIG_HOME/backdrop-randomizer.conf
+    echo '------------------------------------------------------------'
+    echo ' No config file found so creating a fresh one.'
+    echo
+    cat <<EOF > "$XDG_CONFIG_HOME/backdrop-randomizer.conf"
 #
 # $XDG_CONFIG_HOME/backdrop-randomizer.conf
 #
@@ -44,179 +44,181 @@ PIC_PATH=
 # You _MUST_ have rw permissions to the dir you define!
 #SLINK_DIR=/var/lib/backdrop-randomizer
 EOF
-		echo ' Define the path to your pics via the PIC_PATH variable in'
-		echo ' $XDG_CONFIG_HOME/backdrop-randomizer.conf and try again.'
-		echo '------------------------------------------------------------'
-		exit 1
-	else
-		. "$cfg_file"
-	fi
+    echo ' Define the path to your pics via the PIC_PATH variable in'
+    echo ' $XDG_CONFIG_HOME/backdrop-randomizer.conf and try again.'
+    echo '------------------------------------------------------------'
+    exit 1
+  else
+    . "$cfg_file"
+  fi
 
-	# check each var for correctness
-	[[ -z "$MAXDEPTH" ]] && MAXDEPTH=1
-	result=$(echo "$MAXDEPTH" | egrep ^[[:digit:]]+$)
-	if [ "$result" = "" ] ; then
-		echo 'Bad MAXDEPTH in $XDG_CONFIG_HOME/backdrop-randomizer.conf'
-		echo
-		echo 'You have defined a non-integer value.'
-		exit 1
-	fi
+  # check each var for correctness
+  [[ -z "$MAXDEPTH" ]] && MAXDEPTH=1
+  result=$(echo "$MAXDEPTH" | egrep ^[[:digit:]]+$)
+  if [ "$result" = "" ] ; then
+    echo 'Bad MAXDEPTH in $XDG_CONFIG_HOME/backdrop-randomizer.conf'
+    echo
+    echo 'You have defined a non-integer value.'
+    exit 1
+  fi
 
-	[[ -z "$BD_DIR" ]] && BD_DIR=$XDG_CONFIG_HOME
-	if [[ ! -w "$BD_DIR" ]]; then
-		echo "Bad BD_DIR in $XDG_CONFIG_HOME/backdrop-randomizer.conf"
-		echo
-		echo 'You have defined a path to which you cannot write.'
-		exit 1
-	fi
+  [[ -z "$BD_DIR" ]] && BD_DIR=$XDG_CONFIG_HOME
+  if [[ ! -w "$BD_DIR" ]]; then
+    echo "Bad BD_DIR in $XDG_CONFIG_HOME/backdrop-randomizer.conf"
+    echo
+    echo 'You have defined a path to which you cannot write.'
+    exit 1
+  fi
 
-	[[ -z "$SLINK_DIR" ]] && SLINK_DIR=$XDG_CONFIG_HOME
-	if [[ ! -w "$SLINK_DIR" ]]; then
-		echo "Bad SLINK_DIR in $XDG_CONFIG_HOME/backdrop-randomizer.conf"
-		echo
-		echo 'You have defined a path to which you cannot write.'
-		exit 1
-	fi
+  [[ -z "$SLINK_DIR" ]] && SLINK_DIR=$XDG_CONFIG_HOME
+  if [[ ! -w "$SLINK_DIR" ]]; then
+    echo "Bad SLINK_DIR in $XDG_CONFIG_HOME/backdrop-randomizer.conf"
+    echo
+    echo 'You have defined a path to which you cannot write.'
+    exit 1
+  fi
 
-	# use only one find command to both test for pics and to generate pic_database
+  # use only one find command to both test for pics and to generate pic_database
 
-	pic_database="$BD_DIR/backdrop-randomizer.list"
-	[[ ! -f "$pic_database" ]] && find "${PIC_PATH}" -maxdepth "$MAXDEPTH" \
-		-name "*.jpg" -o -name "*.JPG" -o -name "*.png" -o -name "*.PNG" \
-		-o -name "*.gif" -o -name "*.GIF" > "$pic_database" 2>/dev/null
+  pic_database="$BD_DIR/backdrop-randomizer.list"
+  [[ ! -f "$pic_database" ]] && find "${PIC_PATH}" -maxdepth "$MAXDEPTH" \
+    -name "*.jpg" -o -name "*.JPG" -o -name "*.png" -o -name "*.PNG" \
+    -o -name "*.gif" -o -name "*.GIF" > "$pic_database" 2>/dev/null
 
-	howmany=$(wc -l "$pic_database" | awk '{ print $1 }')
+  howmany=$(wc -l "$pic_database" | awk '{ print $1 }')
 
-	if [[ "$howmany" -eq 0 ]]; then
-		echo "Bad PIC_PATH in $XDG_CONFIG_HOME/backdrop-randomizer.conf"
-		echo
-		echo "You have defined a path that contains no pics and/or one that your user cannot access."
-		echo "Supported formats are: jpg, png, and gif."
-		# remove the empty file
-		rm -f "$pic_database"
-		exit 1
-	fi
+  if [[ "$howmany" -eq 0 ]]; then
+    echo "Bad PIC_PATH in $XDG_CONFIG_HOME/backdrop-randomizer.conf"
+    echo
+    echo "You have defined a path that contains no pics and/or one that your user cannot access."
+    echo "Supported formats are: jpg, png, and gif."
+    # remove the empty file
+    rm -f "$pic_database"
+    exit 1
+  fi
 
-	# remove dups in database if they are present
-	uniques=$(gawk ' !x[$0]++' "$pic_database" | wc -l)
-	if [[ "$howmany" != "$uniques" ]]; then
-		gawk ' !x[$0]++' "$pic_database" > /tmp/.backdrop_nodups
-		mv /tmp/.backdrop_nodups "$pic_database"
-		howmany=$(wc -l "$pic_database" | awk '{ print $1 }')
-	fi
+  # remove dups in database if they are present
+  uniques=$(gawk ' !x[$0]++' "$pic_database" | wc -l)
+  if [[ "$howmany" != "$uniques" ]]; then
+    gawk ' !x[$0]++' "$pic_database" > /tmp/.backdrop_nodups
+    mv /tmp/.backdrop_nodups "$pic_database"
+    howmany=$(wc -l "$pic_database" | awk '{ print $1 }')
+  fi
 
-	# do not rotate if screensaver is active or screen is locked
-	# for xscreensaver
-	if [[ -n $(pidof xscreensaver) ]] && [[ -x /usr/bin/xscreensaver-command  ]]; then
-		[[ -n $(xscreensaver-command -time | grep "screen blanked since" 2>/dev/null)  ]]	||
-			[[ -n $(xscreensaver-command -time | grep "screen locked since" 2>/dev/null) ]] &&
-			exit 0
-	fi
+  # do not rotate if screensaver is active or screen is locked
+  # for xscreensaver
+  if [[ -n $(pidof xscreensaver) ]] && [[ -x /usr/bin/xscreensaver-command  ]]; then
+    [[ -n $(xscreensaver-command -time | grep "screen blanked since" 2>/dev/null)  ]]	||
+      [[ -n $(xscreensaver-command -time | grep "screen locked since" 2>/dev/null) ]] &&
+      exit 0
+  fi
 
-	# for xlock
-	[[ -n $(pidof xlock) ]] && exit 0
+  # for xlock
+  [[ -n $(pidof xlock) ]] && exit 0
 
 }
 
 stats() {
-	echo -e " ${BLD}Pics left before next db refresh: ${NRM}${GRN}$howmany${NRM}"
-	echo -e " ${BLD}Current:   ${NRM}${GRN}$(readlink -f "$SLINK_DIR/backdrop-randomizer.jpg")${NRM}"
+  echo -e " ${BLD}Pics left before next db refresh: ${NRM}${GRN}$howmany${NRM}"
+  echo -e " ${BLD}Current:   ${NRM}${GRN}$(readlink -f "$SLINK_DIR/backdrop-randomizer.jpg")${NRM}"
 }
 
 list() {
-	echo " Individual list of pics:"
-	cat "$pic_database"
+  echo " Individual list of pics:"
+  cat "$pic_database"
 }
 
 cycle() {
-	find "${PIC_PATH}" -maxdepth "$MAXDEPTH" -name "*.jpg" -o -name "*.JPG" \
-		-o -name "*.png" -o -name "*.PNG" -o -name "*.gif" \
-		-o -name "*.GIF" > "$pic_database" 2>/dev/null
-	howmany=$(wc -l "$pic_database" | awk '{ print $1 }')
+  find "${PIC_PATH}" -maxdepth "$MAXDEPTH" -name "*.jpg" -o -name "*.JPG" \
+    -o -name "*.png" -o -name "*.PNG" -o -name "*.gif" \
+    -o -name "*.GIF" > "$pic_database" 2>/dev/null
+  howmany=$(wc -l "$pic_database" | awk '{ print $1 }')
 }
 
 randomize() {
-	# two conditions:
-	# 1) 1 line left (one pic left) so use the pic and regenerate the list
-	# 2) 2 or more lines left so select a random number between 1 and $howmany
-	if [[ $howmany -eq 1 ]]; then
-		# condition 1 is true
-		useit=$(sed -n "1 p" "$pic_database") && filename=$(basename "$useit")
+  # two conditions:
+  # 1) 1 line left (one pic left) so use the pic and regenerate the list
+  # 2) 2 or more lines left so select a random number between 1 and $howmany
+  if [[ $howmany -eq 1 ]]; then
+    # condition 1 is true
+    useit=$(sed -n "1 p" "$pic_database") && filename=$(basename "$useit")
 
-		find "${PIC_PATH}" -maxdepth "$MAXDEPTH" -name "*.jpg" -o -name "*.JPG" \
-			-o -name "*.png" -o -name "*.PNG" -o -name "*.gif" \
-			-o -name "*.GIF" > "$pic_database"
+    find "${PIC_PATH}" -maxdepth "$MAXDEPTH" -name "*.jpg" -o -name "*.JPG" \
+      -o -name "*.png" -o -name "*.PNG" -o -name "*.gif" \
+      -o -name "*.GIF" > "$pic_database"
 
-		# exclude the one we just picked to create the illusion that we NEVER repeat :)
-		sed -i "/$filename/d" "$pic_database"
-		ln -sf "$useit" "$SLINK_DIR"/backdrop-randomizer.jpg
-		[[ ! -z $(pidof xfdesktop) ]] && DISPLAY=:0.0 /usr/bin/xfdesktop --reload
-	elif [[ $howmany -ge 2 ]]; then
-		# condition 2 is true
-		rndpick=1
-		while [[ $rndpick -lt 2 ]]; do
-			rndpick=$((RANDOM%howmany+1))
-		done
-		useit=$(sed -n "$rndpick p" "$pic_database") && filename=$(basename "$useit")
+    # exclude the one we just picked to create the illusion that we NEVER repeat :)
+    sed -i "/$filename/d" "$pic_database"
+    ln -sf "$useit" "$SLINK_DIR"/backdrop-randomizer.jpg
+    [[ ! -z $(pidof xfdesktop) ]] && DISPLAY=:0.0 /usr/bin/xfdesktop --reload
+  elif [[ $howmany -ge 2 ]]; then
+    # condition 2 is true
+    rndpick=1
+    while [[ $rndpick -lt 2 ]]; do
+      rndpick=$((RANDOM%howmany+1))
+    done
+    useit=$(sed -n "$rndpick p" "$pic_database") && filename=$(basename "$useit")
 
-		# exclude the one we just picked to create the illusion that we NEVER repeat :)
-		sed -i "/$filename/d" "$pic_database"
-		ln -sf "$useit" "$SLINK_DIR"/backdrop-randomizer.jpg
-		[[ ! -z $(pidof xfdesktop) ]] && DISPLAY=:0.0 /usr/bin/xfdesktop --reload
-	fi
+    # exclude the one we just picked to create the illusion that we NEVER repeat :)
+    sed -i "/$filename/d" "$pic_database"
+    ln -sf "$useit" "$SLINK_DIR"/backdrop-randomizer.jpg
+    [[ ! -z $(pidof xfdesktop) ]] && DISPLAY=:0.0 /usr/bin/xfdesktop --reload
+  fi
 }
 
 add() {
-	if [[ -z "$arg" ]]; then
-		echo -e "${RED}You must provide a supported image.${NRM}"
-		exit 1
-	fi
+  if [[ -z "$arg" ]]; then
+    echo -e "${RED}You must provide a supported image.${NRM}"
+    exit 1
+  fi
 
-	file=$(/usr/bin/readlink -f "$arg")
-	if [[ -n $(echo "$file"| grep -E '*.jpg|*.JPG|*.gif|*.GIF|*.png|*.PNG') ]]; then
-		# check for dups
-		if [[ -n $(grep "$file" "$pic_database") ]]; then
-			echo -e " ${RED}${file##*/}${NRM}${BLD} ---X not added since already present.${NRM}"
-			exit 1
-		fi
+  file=$(/usr/bin/readlink -f "$arg")
+  if [[ -n $(echo "$file"| grep -E '*.jpg|*.JPG|*.gif|*.GIF|*.png|*.PNG') ]]; then
+    # check for dups
+    if [[ -n $(grep "$file" "$pic_database") ]]; then
+      echo -e " ${RED}${file##*/}${NRM}${BLD} ---X not added since already present.${NRM}"
+      exit 1
+    fi
 
-		echo "$file" >> "$pic_database"
-		after=$(wc -l "$pic_database" | awk '{ print $1 }')
-		echo -e " ${GRN}${file##*/}${NRM}${BLD} ---> added to database.${NRM}"
-		echo -e " ${BLD}Database: ${NMR}${RED}$pic_database${NRM}${BLD} now contains ${NRM}${YLW}$after${NRM}${BLD} pics.${NRM}"
-	else
-		echo -e " ${BLD}Not a supported image file: ${NRM}${RED}${file##*/}${NRM}"
-		echo -e " ${BLD}Currently, only jpeg, gif, and png images are supported.${NRM}"
-	fi
+    echo "$file" >> "$pic_database"
+    after=$(wc -l "$pic_database" | awk '{ print $1 }')
+    echo -e " ${GRN}${file##*/}${NRM}${BLD} ---> added to database.${NRM}"
+    echo -e " ${BLD}Database: ${NMR}${RED}$pic_database${NRM}${BLD} now contains ${NRM}${YLW}$after${NRM}${BLD} pics.${NRM}"
+  else
+    echo -e " ${BLD}Not a supported image file: ${NRM}${RED}${file##*/}${NRM}"
+    echo -e " ${BLD}Currently, only jpeg, gif, and png images are supported.${NRM}"
+  fi
 }
 
 case "$1" in
-	A|a)
-		check ; arg="$2" ; add ;;
-	R|r)
-		check
-		# if not logged into X there is nothing to do
-		[[ -n $(ps -u $(whoami) | grep xfce4-session) ]] && randomize
-		;;
-	S|s)
-		check ; stats ;;
-	L|l)
-		check ; list ;;
-	C|c)
-		check ; cycle ; randomize ;;
-	*) 
-		check
-		echo -e "${RED}backdrop-randomizer v$VERS${NRM}"
-		echo
-		stats
-		echo
-		echo -e "${BLD} $0${NRM} ${GRN}{r|l|a|c}${NRM}"
-		echo
-		echo -e "${BLD} r) ${GRN}R${NRM}${BLD}andomly select a pic from the database and refresh xfdesktop."
-		echo -e "${BLD} l) ${GRN}L${NRM}${BLD}ist all pics in the database."
-		echo -e "${BLD} a) ${GRN}A${NRM}${BLD}dd the next token to database."
-		echo -e "${BLD} c) ${GRN}C${NRM}${BLD}lear the database and start anew.${NRM}"
-		echo
-		echo -e " Add all new pics to the database: ${YLW}find -L /path/to/pics -type f -mtime -1 | xargs -n1 bdr a${NRM}"
-		;;
+  A|a)
+    check ; arg="$2" ; add ;;
+  R|r)
+    check
+    # if not logged into X there is nothing to do
+    [[ -n $(ps -u $(whoami) | grep xfce4-session) ]] && randomize
+    ;;
+  S|s)
+    check ; stats ;;
+  L|l)
+    check ; list ;;
+  C|c)
+    check ; cycle ; randomize ;;
+  *) 
+    check
+    echo -e "${RED}backdrop-randomizer v$VERS${NRM}"
+    echo
+    stats
+    echo
+    echo -e "${BLD} $0${NRM} ${GRN}{r|l|a|c}${NRM}"
+    echo
+    echo -e "${BLD} r) ${GRN}R${NRM}${BLD}andomly select a pic from the database and refresh xfdesktop."
+    echo -e "${BLD} l) ${GRN}L${NRM}${BLD}ist all pics in the database."
+    echo -e "${BLD} a) ${GRN}A${NRM}${BLD}dd the next token to database."
+    echo -e "${BLD} c) ${GRN}C${NRM}${BLD}lear the database and start anew.${NRM}"
+    echo
+    echo -e " Add all new pics to the database: ${YLW}find -L /path/to/pics -type f -mtime -1 | xargs -n1 bdr a${NRM}"
+    ;;
 esac
+
+# vim:set ts=2 sw=2 et:
